Scrum 23 - Link player's team to individual teams page
CS464-Group-Project/CS464_GroupProject pull request #10
Opened 2023-11-25 14:36 UTC by lebenpdx

Added the team badge to the players' page that will link to the team's page when clicked

![player_link_to_team](https://github.com/CS464-Group-Project/CS464_GroupProject/assets/116242222/e2299f26-4307-4cea-85e1-3be9a984a5dd)

2023-11-25 16:27 UTC, txiong002 requested changes
A couple of styling and mobile view changes.

2023-11-25 16:27 UTC, txiong002 commented on cs464-group-project/src/pages/Players/PlayersMainPage.js
Starting around line 138, might be a good place to start or place another "row" so you can adjust the number of col if more than one player is being displayed.  Currently at < 768px, its only 1 col.
![adjust_column_number](https://github.com/CS464-Group-Project/CS464_GroupProject/assets/97830813/c7ad9fb5-b59f-42b8-b4ec-5ceae5436875)

2023-11-25 16:27 UTC, txiong002 commented on cs464-group-project/src/pages/Players/IndividualPlayer.js
Could use some spacing away from the nav bar.  Also, would be nice if you can add some kind of effect to the logo, to show user its clickable.  
![image](https://github.com/CS464-Group-Project/CS464_GroupProject/assets/97830813/4f0b8a58-607c-44fb-b00f-977ce0e5a79a)

2023-11-25 17:48 UTC, lebenpdx commented on cs464-group-project/src/pages/Players/IndividualPlayer.js
On hover, the logo now expands slightly, the cursor changes to a pointer and a tooltip pops up
![chrome_5CW7g4MJRv](https://github.com/CS464-Group-Project/CS464_GroupProject/assets/116242222/8d574b73-fc51-4a80-a8c0-59d640da5236)

2023-11-25 17:49 UTC, lebenpdx commented on cs464-group-project/src/pages/Players/PlayersMainPage.js
On screen sizes <768px I now I have it so that there are 2 columns. I think beyond that visibility becomes an issue

![chrome_e1vn7zRSCE](https://github.com/CS464-Group-Project/CS464_GroupProject/assets/116242222/393cbf69-9129-4a6b-a5d9-bfd2fd4699fa)

2023-11-26 01:19 UTC, txiong002 approved these changes

2023-11-26 16:57 UTC, merged