Scrum 26
CS464-Group-Project/CS464_GroupProject pull request #12
Opened 2023-11-28 13:46 UTC by lebenpdx

Designed individual players' page.

Elements
- Heading with player render, name, and player number
- Small bits of player information
- Links to individual team page and social media pages
- Player image
- Timeline of former teams played on, as well as their badges
- List of honours received during career

![chrome_Ks12XegogE](https://github.com/CS464-Group-Project/CS464_GroupProject/assets/116242222/e2d13d1b-e9be-438e-be11-f7b968de769c)
![chrome_FqIlp6r5gm](https://github.com/CS464-Group-Project/CS464_GroupProject/assets/116242222/d9fa71b4-5b8a-410a-905b-1a1ca6da3daf)

2023-11-28 18:39 UTC, txiong002 requested changes
Minor: getting some error/warnings on some components for missing dependcy.

Layout Changes Recommendations: move honours into this col
![image](https://github.com/CS464-Group-Project/CS464_GroupProject/assets/97830813/96664734-e17e-4535-a3f0-78b3ce973233)

You could remove image from the header since you already have pic in cols below:
![header_pic](https://github.com/CS464-Group-Project/CS464_GroupProject/assets/97830813/42d5db56-e36f-41a8-a8e9-8eb9b1a703a6)

2023-11-28 18:39 UTC, txiong002 commented on cs464-group-project/src/components/player/PlayerFormerBadges.jsx
> +  }, []);
gettitng error/warning for missing dependency on line 19

2023-11-28 18:39 UTC, txiong002 commented on cs464-group-project/src/components/player/PlayerFormerTeams.jsx
> +  }, []);
getting error/warnning for missing dependency on line 25

2023-11-28 18:39 UTC, txiong002 commented on cs464-group-project/src/components/player/PlayerHonours.jsx
> +  }, []);
getting error/warning for missing dependency line 18

2023-11-28 20:52 UTC, lebenpdx commented on cs464-group-project/src/components/player/PlayerFormerBadges.jsx
> +  }, []);
Should be fixed now

2023-11-28 20:52 UTC, lebenpdx commented on cs464-group-project/src/components/player/PlayerFormerTeams.jsx
> +  }, []);
Should be fixed now

2023-11-28 20:52 UTC, lebenpdx commented on cs464-group-project/src/components/player/PlayerHonours.jsx
> +  }, []);
Should be fixed now

2023-11-28 20:54 UTC, lebenpdx commented
I removed the image from the header. But I think I prefer the table at the bottom for now. There are some edge case players who have 10+ honours and it messes with the formatting when placed higher up. I tried to set an overflow but I couldn't get the alignment of it to be as consistent as I wanted.
![chrome_SxuaKvC1RY](https://github.com/CS464-Group-Project/CS464_GroupProject/assets/116242222/d4adfb83-8e98-46de-bcc0-623593d8afe6)

2023-11-28 22:47 UTC, txiong002 requested changes
Mobile View Change: Can you center the name and number when window resize for mobile view: 
![image](https://github.com/CS464-Group-Project/CS464_GroupProject/assets/97830813/3b3064d9-b345-4be1-b74a-9c0fbd0f080a)

2023-11-28 23:04 UTC, lebenpdx commented
I centered the heading on mobile view, and switched the info area with the player image
![chrome_ZBZK40ilek](https://github.com/CS464-Group-Project/CS464_GroupProject/assets/116242222/9e9717a0-f3a1-43a3-a2e3-f382511b52e5)

2023-11-28 23:42 UTC, txiong002 commented
> I centered the heading on mobile view, and switched the info area with the player image ![chrome_ZBZK40ilek](https://private-user-images.githubusercontent.com/116242222/286424335-9e9717a0-f3a1-43a3-a2e3-f382511b52e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyMTQ1MDksIm5iZiI6MTcwMTIxNDIwOSwicGF0aCI6Ii8xMTYyNDIyMjIvMjg2NDI0MzM1LTllOTcxN2EwLWYzYTEtNDNhMy1hMmUzLWYzODI1MTFiNTJlNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyOFQyMzMwMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZDBmNWU4YzcxY2NhMjE2NjFjZDg4MDhhNWVmYzg0Mzc1MGM3ZjFiMzVkMjc1MmE0OTE3NmVkYzljY2IyNzUyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jFVd01GNrNWQu0wAIcjXEjCohrKez1atrVskstv4S10)

the alignment is still off a little:
![image](https://github.com/CS464-Group-Project/CS464_GroupProject/assets/97830813/467ff11a-6ef9-4975-bfca-be253fac18f1)

2023-11-29 04:09 UTC, lebenpdx commented
This should be better

![chrome_jJ6JWLxxCl](https://github.com/CS464-Group-Project/CS464_GroupProject/assets/116242222/132a1c05-784f-416d-80dd-4d4f8aeebaf6)

2023-11-29 04:10 UTC, lebenpdx commented
> > I centered the heading on mobile view, and switched the info area with the player image ![chrome_ZBZK40ilek](https://private-user-images.githubusercontent.com/116242222/286424335-9e9717a0-f3a1-43a3-a2e3-f382511b52e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyMTQ1MDksIm5iZiI6MTcwMTIxNDIwOSwicGF0aCI6Ii8xMTYyNDIyMjIvMjg2NDI0MzM1LTllOTcxN2EwLWYzYTEtNDNhMy1hMmUzLWYzODI1MTFiNTJlNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyOFQyMzMwMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZDBmNWU4YzcxY2NhMjE2NjFjZDg4MDhhNWVmYzg0Mzc1MGM3ZjFiMzVkMjc1MmE0OTE3NmVkYzljY2IyNzUyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jFVd01GNrNWQu0wAIcjXEjCohrKez1atrVskstv4S10)
> 
> the alignment is still off a little: ![image](https://private-user-images.githubusercontent.com/97830813/286430736-467ff11a-6ef9-4975-bfca-be253fac18f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyMzExMjQsIm5iZiI6MTcwMTIzMDgyNCwicGF0aCI6Ii85NzgzMDgxMy8yODY0MzA3MzYtNDY3ZmYxMWEtNmVmOS00OTc1LWJmY2EtYmUyNTNmYWMxOGYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDA0MDcwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlZjBhNDlhMmEzNDllZTNjNTYwYTVhZDllMTU2Nzc2OTk0ODNjNWZjNTJlMjU0NzJlZDAzYTVkYjU0N2ZlNWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CAP9PJZdH32RbvNgasKutAK7zhTdJyCKNj3poCPdW0U)

This should be better

![chrome_jJ6JWLxxCl](https://github.com/CS464-Group-Project/CS464_GroupProject/assets/116242222/6ea848a2-bbde-47d9-b160-a6dde7919b83)

2023-11-29 06:27 UTC, txiong002 requested changes
If 
![image](https://github.com/CS464-Group-Project/CS464_GroupProject/assets/97830813/be55c936-e798-4198-980a-facc9a6b1fba)
no honours to display you should put some text  there, or dont display honours.

2023-11-29 06:28 UTC, txiong002 commented
> > > I centered the heading on mobile view, and switched the info area with the player image ![chrome_ZBZK40ilek](https://private-user-images.githubusercontent.com/116242222/286424335-9e9717a0-f3a1-43a3-a2e3-f382511b52e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyMTQ1MDksIm5iZiI6MTcwMTIxNDIwOSwicGF0aCI6Ii8xMTYyNDIyMjIvMjg2NDI0MzM1LTllOTcxN2EwLWYzYTEtNDNhMy1hMmUzLWYzODI1MTFiNTJlNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyOFQyMzMwMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZDBmNWU4YzcxY2NhMjE2NjFjZDg4MDhhNWVmYzg0Mzc1MGM3ZjFiMzVkMjc1MmE0OTE3NmVkYzljY2IyNzUyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jFVd01GNrNWQu0wAIcjXEjCohrKez1atrVskstv4S10)
> > 
> > 
> > the alignment is still off a little: ![image](https://private-user-images.githubusercontent.com/97830813/286430736-467ff11a-6ef9-4975-bfca-be253fac18f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyMzExMjQsIm5iZiI6MTcwMTIzMDgyNCwicGF0aCI6Ii85NzgzMDgxMy8yODY0MzA3MzYtNDY3ZmYxMWEtNmVmOS00OTc1LWJmY2EtYmUyNTNmYWMxOGYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDA0MDcwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlZjBhNDlhMmEzNDllZTNjNTYwYTVhZDllMTU2Nzc2OTk0ODNjNWZjNTJlMjU0NzJlZDAzYTVkYjU0N2ZlNWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CAP9PJZdH32RbvNgasKutAK7zhTdJyCKNj3poCPdW0U)
> 
> This should be better
> 
> ![chrome_jJ6JWLxxCl](https://private-user-images.githubusercontent.com/116242222/286473883-6ea848a2-bbde-47d9-b160-a6dde7919b83.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyMzk1NDMsIm5iZiI6MTcwMTIzOTI0MywicGF0aCI6Ii8xMTYyNDIyMjIvMjg2NDczODgzLTZlYTg0OGEyLWJiZGUtNDdkOS1iMTYwLWE2ZGRlNzkxOWI4My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyOVQwNjI3MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZGU4NmYyNjM3ZDUyZGFhODk1MThjZjZmM2Y0MTdiZjA3Mjc3ZmQyYTBiMzY5MmJjZDQ5MjVhM2U3MmFjNzNmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.92mqrQ0JXiuhw4QuQAqzeBo1h3qMhuUdnfDcIilbPaM)

Alignment looks good now!

2023-11-29 14:41 UTC, lebenpdx commented
> If no honours to display you should put some text there, or dont display honours. ![image](https://private-user-images.githubusercontent.com/97830813/286497394-be55c936-e798-4198-980a-facc9a6b1fba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyNjg1MDksIm5iZiI6MTcwMTI2ODIwOSwicGF0aCI6Ii85NzgzMDgxMy8yODY0OTczOTQtYmU1NWM5MzYtZTc5OC00MTk4LTk4MGEtZmFjYzlhNmIxZmJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDE0MzAwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4MWM2NzhlNDk4YzliNTU5MzViYTA4OWVmOWM5NWFjYTFlYjI3NDAzYmJjNTZjMjZiM2QxY2I0YzNlMTg0ZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YMcRvZekN0uptta2FNBQbIjdtdLMyrvueS6CIx66zNY)

I went with populating the table with "No career honours"
![chrome_BSB9RDG5Wg](https://github.com/CS464-Group-Project/CS464_GroupProject/assets/116242222/0b51acb7-8e77-4e04-a6f7-031ad95d7620)

2023-11-29 20:24 UTC, txiong002 approved these changes
Everything looks good now.  Good work!

2023-11-29 20:29 UTC, merged