Navbar
CS464-Group-Project/CS464_GroupProject pull request #3
Opened 2023-11-13 05:32 UTC by dvan2

Hey guys.  I tried to clean up the Navbar using react boot strap: https://react-bootstrap.netlify.app/docs/components/navbar/

Let me know if there's any suggestion.

2023-11-13 22:06 UTC, txiong002 commented on cs464-group-project/src/components/navigationBar/NavBar.js
> +import Container from "react-bootstrap/Container";
Remove if not using Container

2023-11-13 22:08 UTC, txiong002 requested changes
Can you add some contrast to the nav bar and when it hovering, its really hard to see

2023-11-14 04:10 UTC, txiong002 requested changes
Can you center the text when opening the hambuger window. Also can  you make the underline just span the length of text  when in hambuger mode.
![image](https://github.com/CS464-Group-Project/CS464_GroupProject/assets/97830813/2c3beee3-cfb5-43f9-a736-2fc1694c2734)

2023-11-14 07:10 UTC, dvan2 commented
> Can you center the text when opening the hambuger window. Also can you make the underline just span the length of text when in hambuger mode. ![image](https://user-images.githubusercontent.com/97830813/282660122-2c3beee3-cfb5-43f9-a736-2fc1694c2734.png)

Here is the new Update: 
![image](https://github.com/CS464-Group-Project/CS464_GroupProject/assets/122697354/762484e8-b74e-4f6d-8586-67d340268feb)

2023-11-14 08:09 UTC, txiong002 approved these changes
Looks good!

2023-11-14 08:29 UTC, merged